### PR TITLE
Added diacos check

### PR DESCRIPTION
**Pull request by slalomsk8er**
This plugin does a function and performance check of a ID DIACOS® installation by authenticating and doing a search.

### CODE REVIEW

**Comment by markuslf** [comment]
Thank you for your contribution. We will review and integrate it in May.

**Comment by markuslf** [comment]
Could you check in three example files for our unit tests?
* `examples/EXAMPLE01-login` containing anonymized JSON output from `/axis2/idlogikrest?__format__=json&serviceName=user.Login&COMPUTER={}&IP={}&NAME={}&LICENCE={}`
* `examples/EXAMPLE01-searchDiagnoses` containing anonymized JSON output from `/axis2/idlogikrest?__format__=json&serviceName=classification.SearchDiagnoses&COUNTRY={}&YEAR={}&FORMAT={}&SORT_MODE={}&CONCEPT_FILTER={}&SESSION_ID={}&SEARCHTEXT={}`
* `examples/EXAMPLE01-logoff` containing anonymized JSON output from `/axis2/idlogikrest?__format__=json&serviceName=user.Logoff&SESSION_ID={}`

**Comment by slalomsk8er** [comment]
Are the added examples fit for purpose?

**Comment by markuslf** [comment]
> Are the added examples fit for purpose?

Exactly what I asked for, thank you.

**Pull request merged**
